# Generated by Django 4.0.1 on 2022-12-01 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_remove_customuser_number_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
